VM_DEFINITIONS = {
    "debian-vm": {
        box: "debian-13-vbox",
        base_name_vm: "debian-vm",
        base_ip_octet: 20
    },
    "ubuntu-vm": {
        box: "ubuntu-24.04-lts-vbox",
        base_name_vm: "ubuntu-vm",
        base_ip_octet: 30
    }
}

COUNT_VM = 2

VM_MEMORY = 4096
VM_CORES = 2

SSH_USER = "root"

SUBNET = "192.168.56."

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false

    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    config.ssh.username = SSH_USER
    config.ssh.private_key_path = "D://app_data//git_home//.ssh//keys//build//packer//key.pem"

    config.vm.synced_folder ".", "/vagrant", disabled: true 

    VM_DEFINITIONS.each do |key, vm_def|
        (1..COUNT_VM).each do |vm_id|
            
            instance_name = "#{vm_def[:base_name_vm]}#{vm_id}" 
            
            ip_suffix = vm_def[:base_ip_octet] + (vm_id - 1)
            static_ip = "#{SUBNET}#{ip_suffix}" 

            config.vm.define instance_name do |item|
                item.vm.box = vm_def[:box]
                
                item.vm.network "private_network", ip: static_ip
                
                item.vm.provider "virtualbox" do |vb|
                    vb.name = instance_name
                    vb.memory = VM_MEMORY
                    vb.cpus = VM_CORES
                end
            end
        end
    end
end